-- SNG Logistics Database Dump
-- Generated by custom Node.js script

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `cod_settlements`;
CREATE TABLE `cod_settlements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `cod_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `collected_at` timestamp NULL DEFAULT NULL,
  `remitted_at` timestamp NULL DEFAULT NULL,
  `remitted_to` varchar(180) DEFAULT NULL,
  `status` enum('PENDING','COLLECTED','REMITTED') NOT NULL DEFAULT 'PENDING',
  `note` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_cod_order` (`order_id`),
  CONSTRAINT `fk_cod_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('person','shop') NOT NULL DEFAULT 'shop',
  `name` varchar(180) NOT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `country` varchar(60) DEFAULT NULL,
  `province` varchar(120) DEFAULT NULL,
  `city` varchar(120) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `tax_id` varchar(60) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_status_logs`;
CREATE TABLE `order_status_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `from_status` varchar(40) DEFAULT NULL,
  `to_status` varchar(40) NOT NULL,
  `note` text DEFAULT NULL,
  `action_by` bigint unsigned DEFAULT NULL,
  `action_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_logs_order` (`order_id`),
  KEY `fk_logs_user` (`action_by`),
  CONSTRAINT `fk_logs_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `fk_logs_user` FOREIGN KEY (`action_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `job_no` varchar(50) NOT NULL,
  `direction` enum('TH_TO_LA','LA_TO_TH') NOT NULL,
  `sender_id` bigint unsigned DEFAULT NULL,
  `receiver_id` bigint unsigned DEFAULT NULL,
  `service_type` varchar(60) DEFAULT NULL,
  `declared_weight` decimal(10,2) DEFAULT NULL,
  `declared_size` varchar(60) DEFAULT NULL,
  `declared_value` decimal(12,2) DEFAULT NULL,
  `actual_weight` decimal(10,2) DEFAULT NULL,
  `actual_size` varchar(60) DEFAULT NULL,
  `price_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `price_currency` char(3) NOT NULL DEFAULT 'THB',
  `cod_amount` decimal(12,2) DEFAULT '0.00',
  `requires_customs` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(40) NOT NULL DEFAULT 'NEW',
  `trip_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_no` (`job_no`),
  KEY `fk_orders_sender` (`sender_id`),
  KEY `fk_orders_receiver` (`receiver_id`),
  CONSTRAINT `fk_orders_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `customers` (`id`),
  CONSTRAINT `fk_orders_sender` FOREIGN KEY (`sender_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `type` enum('freight','customs','fee') NOT NULL DEFAULT 'freight',
  `method` enum('cash','transfer','other') NOT NULL DEFAULT 'transfer',
  `amount` decimal(12,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'THB',
  `paid_at` timestamp NULL DEFAULT NULL,
  `ref_no` varchar(120) DEFAULT NULL,
  `status` enum('PENDING','PAID','FAILED') NOT NULL DEFAULT 'PENDING',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_payments_order` (`order_id`),
  CONSTRAINT `fk_payments_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `shipping_rates`;
CREATE TABLE `shipping_rates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `max_weight` decimal(10,2) NOT NULL,
  `max_dimension` int NOT NULL DEFAULT '0' COMMENT 'Sum of W+L+H in cm',
  `price` decimal(10,2) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `shipping_rates` VALUES (1,'A','1.00',30,'30.00',1,'2025-12-08 12:44:35',NULL),
(2,'A+','2.00',40,'40.00',1,'2025-12-08 13:32:31',NULL);

DROP TABLE IF EXISTS `trip_orders`;
CREATE TABLE `trip_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `trip_id` bigint unsigned NOT NULL,
  `order_id` bigint unsigned NOT NULL,
  `loaded_at` timestamp NULL DEFAULT NULL,
  `unloaded_at` timestamp NULL DEFAULT NULL,
  `sequence_no` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_trip_order` (`trip_id`,`order_id`),
  KEY `fk_trip_orders_order` (`order_id`),
  CONSTRAINT `fk_trip_orders_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `fk_trip_orders_trip` FOREIGN KEY (`trip_id`) REFERENCES `trips` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `trips`;
CREATE TABLE `trips` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `trip_no` varchar(50) NOT NULL,
  `trip_date` date DEFAULT NULL,
  `vehicle` varchar(80) DEFAULT NULL,
  `driver_name` varchar(120) DEFAULT NULL,
  `origin_border` varchar(120) DEFAULT NULL,
  `dest_border` varchar(120) DEFAULT NULL,
  `status` enum('PLANNED','ON_ROUTE','CROSSING','ARRIVED','CLOSED') NOT NULL DEFAULT 'PLANNED',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `trip_no` (`trip_no`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('admin','staff','manager','thai_warehouse','lao_warehouse') NOT NULL DEFAULT 'staff',
  `name` varchar(120) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `status` enum('active','disabled') NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



SET FOREIGN_KEY_CHECKS=1;
